### PR TITLE
Feature: "Contact Us" page. Issues eliminated.

### PR DESCRIPTION
**Pull request by antonmorya**

### CODE REVIEW

**Comment by soloviovmax** [comment]
@antonmorya After merging into the master will be automatically launched deploy but it's broken. Need merge into dev and then deploy it manually. Dev is our main branch.

**Comment by antonmorya** [comment]
@soloviovmax Thanks! Changed base to Dev.

**Comment by DarkOverkill** [comment]
@antonmorya Could you please fix lint errors?

**Comment by antonmorya** [comment]
@DarkOverkill No problems. Done.

**Pull request merged**
